### ISSUE TITLE
io_ctrl_top is missing

### ISSUE THREAD

**Issue by jimaandro** [PrincetonUniversity/openpiton#143]
Hi
I want to add a new device (actually to add an extra AXI port on sd_top, connected to the xbar). The manual says "To add a new devices, an entry has to be added to the devices.xml file and the top-level module needs to be **instantiated in io_ctrl_top**." . But there is no file named io_ctrl_top. 
Am I missing something?

**Comment by Jbalkind** [comment]
The doc is outdated. The file is chipset_impl.v.pyv
