### ISSUE TITLE
Load large file from pitonstream

### ISSUE THREAD

**Issue by jimaandro** [PrincetonUniversity/openpiton#146]
Hello.
Is there any way to load a file via pitonstream? I want to test the RAM, so I want to load a file and print it in uart using pitonstream

**Comment by Jbalkind** [comment]
You can likely use a .incbin directive in the assembly and then point it with its own section inside the linker script (ariane.ld): https://stackoverflow.com/questions/327609/include-binary-file-with-gnu-ld-linker-script
