### ISSUE TITLE
bram_test hello_world

### ISSUE THREAD

**Issue by ljh-num1** [PrincetonUniversity/openpiton#153]
Hi, 
I want to ensure that:
If i run the below three commands, the generated bit will print hello world on the uart console after reset? 
1  $MODEL_DIR:  sims -sys=manycore -x_tiles=1 -y_tiles=1 -msm_build -ariane
2  $MODEL_DIR:  sims -sys=manycore -msm_run -x_tiles=1 -y_tiles=1 hello_world.c -ariane -rtl_timeout 10000000
3  $PITON_ROOT: protosyn -b vcu118 -d system --core=ariane --bram-test hello_world
And the coe will put in which ram?  
Thanks!

**Comment by Jbalkind** [comment]
Theoretically, yes. I will say that the bram-test flow hasn't been thoroughly tested for a while. The last time I tried it (I think on nexys4ddr), it printed but it also then ran some other code after the test finished. If you hit issues let me know and I'm happy to help debug!

**Comment by ljh-num1** [comment]
![image](https://github.com/user-attachments/assets/90898db8-1b65-41cb-b4d6-626b767cfba4)

What's this mean? Test failed!   
When protosyn , it will test hello_world?   
I already run sims , it passed.

**Comment by ljh-num1** [comment]
The  logs are below:
![image](https://github.com/user-attachments/assets/1557d33c-03c3-49c2-b7f5-9873dca733d4)
The compilation.log is passed, the detailed command is as below:
![image](https://github.com/user-attachments/assets/749a2863-aec7-42eb-b25f-65fa28f628d1)
The simulation.log is as below:
![image](https://github.com/user-attachments/assets/11d47061-efd0-4962-9957-6028068518f9)
The results inicate that hello world is an unprocessed argument. So how can i use the argument --bram-test. Can you give me an example? 
thanks!

**Comment by Jbalkind** [comment]
The test is probably called hello_world.c, not just hello_world?

**Comment by ljh-num1** [comment]
I passed with the command "protosyn -b vcu118 -d system --core=ariane --bram-test hello_world.c".  Then i generated the project and bit .
I saw the prj didn't have mc and sd. Is that noraml?
Then i tested the bit. After loading bit, i changed sys_rst_n form 1->0. Then the uart print this:
![image](https://github.com/user-attachments/assets/df848408-27e7-48cf-9b3c-31be8ceefd07)

When protosyn , this files are generated.  
![image](https://github.com/user-attachments/assets/30f55b98-9a27-4e62-ba08-a38862c39e86)

And the fake_uart.log is as below, And I think after loading bit, it should print like :
![image](https://github.com/user-attachments/assets/c9a7918e-9b64-4e7b-9b11-4502e16d1234)

**Comment by ljh-num1** [comment]
Why it initialized sd? I think it should work from ram. Some switch should be selected?

**Comment by ljh-num1** [comment]
I thind maybe the bootrom is error? it shouldn't initialize sd .  How can i change it or where can i get a right bootrom.v?

**Comment by ljh-num1** [comment]
![image](https://github.com/user-attachments/assets/1eadca2d-2742-44b3-a44b-0db825fa86fd)
I find this ,but i don't know how to change it. I did't find some descriptions about this.

**Comment by Jbalkind** [comment]
As I said, this configuration hasn't been tested for a long time. It was designed before the Ariane core was added and once we had DRAM and pitonstream working, we didn't have a lot of reason to use it. When I booted on nexys4ddr a design with --bram-test, it behaved weirdly, like it printed the test output and then ran the bootrom or something else that was strange like that.

I think probably you should check whether or not the PITONSYS_UART_BOOT or a similar macro is set. Either that or you should check the value of the uart_boot_en wire and change it for this configuration. That's probably what is controlling whether to use the linux bootrom or the bare metal bootrom.

**Comment by ljh-num1** [comment]
ok, thanks.
