### ISSUE TITLE
Support for VCU118

### ISSUE THREAD

**Issue by AnouarNechi** [PrincetonUniversity/openpiton#60]
I can see already that there is a folder for the VCU118 board but when I read the documentation it is mentioned that there is only support for three boards and the VCU118 is not included.
So is it really supported or not?

**Comment by fei-g** [comment]
The documentation you read is out-dated. VCU118 is supported. You can have a look at the file `openpiton/piton/tools/src/proto/board.list` to see all the boards supported.
