### ISSUE TITLE
missing file ariane.dts when generating bitstream for vcu118

### ISSUE THREAD

**Issue by AnouarNechi** [PrincetonUniversity/openpiton#61]
I followed the following instruction as mentionned in the readme:
```
export PITON_ROOT=$PWD
source $PITON_ROOT/piton/piton_settings.bash
source piton/ariane_setup.sh
piton/ariane_build_tools.sh
```
 and I got no error (except for aws submodule cannot clone it)
then I executed
protosyn -b vcu118 -d system --core=ariane --uart-dmw ddr
and I got an error I checked the log file :
`Traceback (most recent call last):
  File "<string>", line 18, in <module>
  File "/home/nechi/openpiton/piton/tools/bin/riscvlib.py", line 330, in gen_riscv_dts
    with open(dtsPath + '/ariane.dts','w') as file:
IOError: [Errno 2] No such file or directory: '/home/nechi/openpiton/piton/design/chip/tile/ariane//openpiton/bootrom//ariane.dts'
    while executing
"exec pyhp.py ${PYV_IMPL_FILE} > ${GEN_RTL_IMPL_FILE}"
...`

**Comment by Jbalkind** [comment]
The submodule error is the error that's stopping things from working. Try switching to the openpiton-dev branch and running ariane_setup again. We changed the script more recently which may resolve some of the issue
